name: Node.js CI

on:
  push:
    paths:
      - "**/*.mermaid"
      - "**/*.mmd"
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install mermaid-cli
        run: npm i

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36

      - name: Compile Mermaid
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            npx -p @mermaid-js/mermaid-cli mmdc -i $file -o  $file".svg"
          done

      - name: Push mmd
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Push Mermaid Diagram"
          git push origin HEAD:${GITHUB_REF}
